pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build & Test') {
            steps {
                sh 'mvn -B clean test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                    publishHTML(target: [reportName: 'Extent Reports', reportDir: 'target/ExtentReports', reportFiles: 'index.html'])
                }
            }
        }
    }
}
